Added check for compilers that may not enable RTTI by default

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2407,6 +2407,58 @@ fi
 #   AC_MSG_RESULT(no)
 # fi
 
+echo "$as_me:$LINENO: checking if compiler uses RTTI by default" >&5
+echo $ECHO_N "checking if compiler uses RTTI by default... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+
+#include <typeinfo>
+int main(int ac,char **av)
+{
+  class A
+  {
+    public:
+      virtual void fred() { }
+  };
+  class B : public A
+  {
+    public:
+      void fred() { }
+  };
+  B t;
+  A * p = dynamic_cast<A *>(&t);
+  return 0;
+}
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  DEFAULT_RTTI=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+DEFAULT_RTTI=0
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+if test "$DEFAULT_RTTI" = "1" ; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  STDCXXFLAGS="$STDCCFLAGS -rtti"
+fi
+
 GCSECTIONS=0
 
 echo "$as_me:$LINENO: checking if linker accepts --gc-sections" >&5
