Applied patch #1240770 Fixed problem with compilation under Solaris 10 Thanks to Boris Pavacic

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3321,6 +3321,69 @@ echo "${ECHO_T}$_FD_SETSIZE" >&6
 fi
 
 
+
+if test "${OSTYPE:-unknown}" = "solaris"; then
+  echo "$as_me:$LINENO: checking for upad128_t" >&5
+echo $ECHO_N "checking for upad128_t... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/types.h>
+int
+main ()
+{
+upad128_t upad; upad._q = 0.0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  has_upad128_t=y
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+  if test ${has_upad128_t} == "y"; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    cat >>confdefs.h <<\_ACEOF
+#define P_HAS_UPAD128_T 1
+_ACEOF
+
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+fi
+
+
+
 if test ${OSTYPE} != Darwin ; then
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -5018,6 +5081,7 @@ _ACEOF
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
     fi
+    LIBS=""
   fi
 
   if test "${HAS_RESOLVER}z" = "z" ; then
@@ -5170,61 +5234,8 @@ echo "${ECHO_T}yes" >&6
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
     fi
-  fi
-
-  if test "${HAS_RESOLVER}z" = "z" ; then
-    echo "$as_me:$LINENO: checking for res_search in C library" >&5
-echo $ECHO_N "checking for res_search in C library... $ECHO_C" >&6
     LIBS=""
-    cat >conftest.$ac_ext <<_ACEOF
-
-#include <sys/types.h>
-#include <netinet/in.h>
-#include <resolv.h>
-int main(int argc,char **argv){
- res_search (NULL, 0, 0, NULL, 0);
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_cxx_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  HAS_RESOLVER=1
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-    if test "${HAS_RESOLVER:-unset}" != "unset" ; then
-      echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-      RESOLVER_LIBS=""
-    else
-      echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-    fi
   fi
-
 
   if test "${HAS_RESOLVER}z" = "z" ; then
     echo "$as_me:$LINENO: checking for library containing __res_search" >&5
