Fixed IPV6 problems and Darwin system identification
git-svn-id: svn://svn.code.sf.net/p/opalvoip/code/ptlib/trunk@7799 023b2edf-31b2-4de3-b41e-bca80c47788f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1050,7 +1050,7 @@ case "$target_os" in
 		   OSRELEASE="5.$OSVER" ;
                    STDCCFLAGS="-DP_SOLARIS=$OSRELEASE" ;;
 
-  darwin)	   OSTYPE=Darwin ;
+  darwin* )	   OSTYPE=Darwin ;
 		   OSRELEASE=`uname -r` ;
                    STDCCFLAGS="-DP_MACOSX=$OSRELEASE -DNO_LONG_DOUBLE";;
 
@@ -2852,7 +2852,55 @@ if test $ac_cv_file__proc_net_if_inet6 = yes; then
   HAS_IPV6=1
 fi
 
-if test "${HAVE_IPV6:-unset}" != "unset" ; then
+for ac_header in linux/in6.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:2858: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line 2864 "configure"
+#include "confdefs.h"
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:2868: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:2874: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  eval "$as_ac_Header=no"
+fi
+rm -f conftest.err conftest.$ac_ext
+fi
+echo "$as_me:2893: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<EOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+EOF
+ HAS_IPV6=1
+fi
+done
+
+if test "${HAS_IPV6:-unset}" != "unset" ; then
 
 cat >>confdefs.h <<\EOF
 #define P_HAS_IPV6 1
@@ -2860,23 +2908,23 @@ EOF
 
 fi
 
-echo "$as_me:2863: checking for linux/videodev.h" >&5
+echo "$as_me:2911: checking for linux/videodev.h" >&5
 echo $ECHO_N "checking for linux/videodev.h... $ECHO_C" >&6
 if test "${ac_cv_header_linux_videodev_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   cat >conftest.$ac_ext <<_ACEOF
-#line 2869 "configure"
+#line 2917 "configure"
 #include "confdefs.h"
 #include <linux/videodev.h>
 _ACEOF
-if { (eval echo "$as_me:2873: \"$ac_cpp conftest.$ac_ext\"") >&5
+if { (eval echo "$as_me:2921: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
   ac_status=$?
   egrep -v '^ *\+' conftest.er1 >conftest.err
   rm -f conftest.er1
   cat conftest.err >&5
-  echo "$as_me:2879: \$? = $ac_status" >&5
+  echo "$as_me:2927: \$? = $ac_status" >&5
   (exit $ac_status); } >/dev/null; then
   if test -s conftest.err; then
     ac_cpp_err=$ac_c_preproc_warn_flag
@@ -2895,7 +2943,7 @@ else
 fi
 rm -f conftest.err conftest.$ac_ext
 fi
-echo "$as_me:2898: result: $ac_cv_header_linux_videodev_h" >&5
+echo "$as_me:2946: result: $ac_cv_header_linux_videodev_h" >&5
 echo "${ECHO_T}$ac_cv_header_linux_videodev_h" >&6
 if test $ac_cv_header_linux_videodev_h = yes; then
   HAS_LINUX_VIDEODEV_H=1
@@ -3000,7 +3048,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:3003: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:3051: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -3172,7 +3220,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:3175: error: ambiguous option: $1
+    { { echo "$as_me:3223: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3191,7 +3239,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:3194: error: unrecognized option: $1
+  -*) { { echo "$as_me:3242: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -3228,7 +3276,7 @@ do
   # Handling of arguments.
   "make/ptbuildopts.mak" ) CONFIG_FILES="$CONFIG_FILES make/ptbuildopts.mak" ;;
   "include/ptbuildopts.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/ptbuildopts.h" ;;
-  *) { { echo "$as_me:3231: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3279: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3446,7 +3494,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3449: creating $ac_file" >&5
+    { echo "$as_me:3497: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3464,7 +3512,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3467: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3515: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3477,7 +3525,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3480: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3528: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3537,7 +3585,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:3540: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:3588: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -3548,7 +3596,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3551: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3599: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3561,7 +3609,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3564: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3612: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3678,7 +3726,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:3681: $ac_file is unchanged" >&5
+      { echo "$as_me:3729: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
