Added configure.in check for recursive mutexes, and changed implementation without recursive mutexes to use PCriticalSection or atomic word structs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3013,8 +3013,8 @@ else
 fi
 
   if test ${HAS_SEMAPHORES_XPG6} = yes ; then
-    echo "$as_me:$LINENO: checking if sem_timedwait will compile" >&5
-echo $ECHO_N "checking if sem_timedwait will compile... $ECHO_C" >&6
+    echo "$as_me:$LINENO: checking if sem_timedwait is compilable" >&5
+echo $ECHO_N "checking if sem_timedwait is compilable... $ECHO_C" >&6
     cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -3065,6 +3065,57 @@ echo "${ECHO_T}no" >&6
     fi
   fi
 fi
+
+P_HAS_RECURSIVE_MUTEX=0
+echo "$as_me:$LINENO: checking if recursive mutexes are available" >&5
+echo $ECHO_N "checking if recursive mutexes are available... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pthread.h>
+int
+main ()
+{
+pthread_mutexattr_t attr; pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE_NP);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  P_HAS_RECURSIVE_MUTEX=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+if test ${P_HAS_RECURSIVE_MUTEX} = 1 ; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+cat >>confdefs.h <<_ACEOF
+#define P_HAS_RECURSIVE_MUTEX ${P_HAS_RECURSIVE_MUTEX}
+_ACEOF
+
+
 
 
 ac_ext=cc
