Made IPV6 support contingent on getnameinfo

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5732,13 +5732,51 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 fi
 echo "$as_me:$LINENO: result: $HAS_IPV6" >&5
 echo "${ECHO_T}$HAS_IPV6" >&6
-
   if test $HAS_IPV6 = yes ; then
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/socket.h>
+                     #include <netdb.h>
+int
+main ()
+{
+getnameinfo(NULL, 0, NULL, 0, NULL, 0, 0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  HAS_IPV6=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+HAS_IPV6=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+    if test $HAS_IPV6 = yes ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define P_HAS_IPV6 1
 _ACEOF
 
+    fi
   fi
 fi
 
