Made failure to detect pthreads a fatal error. Fixed -ffunction-sections detcetion so also checks for -Wl,--gc-sections

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2575,56 +2575,6 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-GCSECTIONS=0
-
-echo "$as_me:$LINENO: checking if compiler accepts -ffunction-sections" >&5
-echo $ECHO_N "checking if compiler accepts -ffunction-sections... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-int main(int ac,char **av) { return 0; }
-_ACEOF
-$CC $CFLAGS -ffunction-sections -c conftest.c > /dev/null 2>&1
-if test $? = 0 ; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-  STDCCFLAGS="$STDCCFLAGS -ffunction-sections"
-  GCSECTIONS=1
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-echo "$as_me:$LINENO: checking if compiler accepts -fdata-sections" >&5
-echo $ECHO_N "checking if compiler accepts -fdata-sections... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-int main(int ac,char **av) { return 0; }
-_ACEOF
-$CC $CFLAGS -fdata-sections -c conftest.c > /dev/null 2>&1
-if test $? = 0 ; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-  STDCCFLAGS="$STDCCFLAGS -fdata-sections"
-  GCSECTIONS=1
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-echo "$as_me:$LINENO: checking if compiler accepts -fvtable-gc" >&5
-echo $ECHO_N "checking if compiler accepts -fvtable-gc... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-int main(int ac,char **av) { return 0; }
-_ACEOF
-$CPLUSPLUS $CFLAGS -fvtable-gc -c conftest.c > /dev/null 2>&1
-if test $? = 0 ; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-  STDCCFLAGS="$STDCCFLAGS -fvtable-gc"
-  GCSECTIONS=1
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
 echo "$as_me:$LINENO: checking if compiler accepts -fno-rtti" >&5
 echo $ECHO_N "checking if compiler accepts -fno-rtti... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
@@ -2640,10 +2590,230 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-if test $GCSECTIONS = 1; then
-  if test "${OSTYPE}" != "Darwin" ; then
-    LDFLAGS="$LDFLAGS -Wl,--gc-sections"
+GCSECTIONS=0
+
+echo "$as_me:$LINENO: checking if linker accepts --gc-sections" >&5
+echo $ECHO_N "checking if linker accepts --gc-sections... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+int main(int ac,char **av) { return 0; }
+_ACEOF
+$CC $CFLAGS -Wl,--gc-sections conftest.c > /dev/null 2>&1
+if test $? = 0 ; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+  echo "$as_me:$LINENO: checking if compiler accepts -ffunction-sections" >&5
+echo $ECHO_N "checking if compiler accepts -ffunction-sections... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+int main(int ac,char **av) { return 0; }
+_ACEOF
+  $CC $CFLAGS -ffunction-sections -c conftest.c > /dev/null 2>&1
+  if test $? = 0 ; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    STDCCFLAGS="$STDCCFLAGS -ffunction-sections"
+    GCSECTIONS=1
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
   fi
+
+  echo "$as_me:$LINENO: checking if compiler accepts -fdata-sections" >&5
+echo $ECHO_N "checking if compiler accepts -fdata-sections... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+int main(int ac,char **av) { return 0; }
+_ACEOF
+  $CC $CFLAGS -fdata-sections -c conftest.c > /dev/null 2>&1
+  if test $? = 0 ; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    STDCCFLAGS="$STDCCFLAGS -fdata-sections"
+    GCSECTIONS=1
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+
+  echo "$as_me:$LINENO: checking if compiler accepts -fvtable-gc" >&5
+echo $ECHO_N "checking if compiler accepts -fvtable-gc... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+int main(int ac,char **av) { return 0; }
+_ACEOF
+  $CPLUSPLUS $CFLAGS -fvtable-gc -c conftest.c > /dev/null 2>&1
+  if test $? = 0 ; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    STDCCFLAGS="$STDCCFLAGS -fvtable-gc"
+    GCSECTIONS=1
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+
+  if test $GCSECTIONS = 1; then
+    if test "${OSTYPE}" != "Darwin" ; then
+      LDFLAGS="$LDFLAGS -Wl,--gc-sections"
+    fi
+  fi
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+
+
+echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
+echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
+if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lpthread  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pthread_create ();
+int
+main ()
+{
+pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_pthread_pthread_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_pthread_pthread_create=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
+echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6
+if test $ac_cv_lib_pthread_pthread_create = yes; then
+  HAS_PTHREADS=yes
+else
+  HAS_PTHREADS=no
+fi
+
+if test ${HAS_PTHREADS} = yes ; then
+  ENDLDLIBS="$ENDLDLIBS -lpthread"
+  STDCCFLAGS="$STDCCFLAGS -D_REENTRANT"
+else
+    echo "$as_me:$LINENO: checking for pthread_create in -lc_r" >&5
+echo $ECHO_N "checking for pthread_create in -lc_r... $ECHO_C" >&6
+if test "${ac_cv_lib_c_r_pthread_create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lc_r  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char pthread_create ();
+int
+main ()
+{
+pthread_create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_c_r_pthread_create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_c_r_pthread_create=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_c_r_pthread_create" >&5
+echo "${ECHO_T}$ac_cv_lib_c_r_pthread_create" >&6
+if test $ac_cv_lib_c_r_pthread_create = yes; then
+  HAS_PTHREADS=yes
+else
+  HAS_PTHREADS=no
+fi
+
+  if test ${HAS_PTHREADS} = yes ; then
+    ENDLDLIBS="$ENDLDLIBS -pthread"
+    STDCCFLAGS="$STDCCFLAGS -D_REENTRANT -pthread"
+  fi
+fi
+
+
+if test ${HAS_PTHREADS} != yes ; then
+  { { echo "$as_me:$LINENO: error: must have pthreads!
+See \`config.log' for more details." >&5
+echo "$as_me: error: must have pthreads!
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define P_PTHREADS 1
+_ACEOF
+
+if test ${OSTYPE} != Darwin ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define P_HAS_SEMAPHORES 1
+_ACEOF
+
 fi
 
 ac_ext=c
@@ -4623,155 +4793,6 @@ fi
 
 
 
-
-
-
-
-echo "$as_me:$LINENO: checking for pthread_create in -lpthread" >&5
-echo $ECHO_N "checking for pthread_create in -lpthread... $ECHO_C" >&6
-if test "${ac_cv_lib_pthread_pthread_create+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lpthread  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char pthread_create ();
-int
-main ()
-{
-pthread_create ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_pthread_pthread_create=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_pthread_pthread_create=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_pthread_pthread_create" >&5
-echo "${ECHO_T}$ac_cv_lib_pthread_pthread_create" >&6
-if test $ac_cv_lib_pthread_pthread_create = yes; then
-  HAS_PTHREADS=yes
-else
-  HAS_PTHREADS=no
-fi
-
-if test ${HAS_PTHREADS} = yes ; then
-  ENDLDLIBS="$ENDLDLIBS -lpthread"
-  STDCCFLAGS="$STDCCFLAGS -D_REENTRANT"
-else
-    echo "$as_me:$LINENO: checking for pthread_create in -lc_r" >&5
-echo $ECHO_N "checking for pthread_create in -lc_r... $ECHO_C" >&6
-if test "${ac_cv_lib_c_r_pthread_create+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lc_r  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char pthread_create ();
-int
-main ()
-{
-pthread_create ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_c_r_pthread_create=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_c_r_pthread_create=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_c_r_pthread_create" >&5
-echo "${ECHO_T}$ac_cv_lib_c_r_pthread_create" >&6
-if test $ac_cv_lib_c_r_pthread_create = yes; then
-  HAS_PTHREADS=yes
-else
-  HAS_PTHREADS=no
-fi
-
-  if test ${HAS_PTHREADS} = yes ; then
-    ENDLDLIBS="$ENDLDLIBS -pthread"
-    STDCCFLAGS="$STDCCFLAGS -D_REENTRANT -pthread"
-  fi
-fi
-
-
-if test ${HAS_PTHREADS} = yes ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define P_PTHREADS 1
-_ACEOF
-
-        if test ${OSTYPE} != Darwin ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define P_HAS_SEMAPHORES 1
-_ACEOF
-
-  fi
-fi
 
 
 
