Add test for setpgrp variants

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3595,6 +3595,8 @@ elif test "${enable_minsize}x" = "yesx" ; then
 fi
 
 
+
+
 # Make sure we can run config.sub.
 $SHELL "$ac_aux_dir/config.sub" sun4 >/dev/null 2>&1 ||
   { { echo "$as_me:$LINENO: error: cannot run $SHELL $ac_aux_dir/config.sub" >&5
@@ -7664,6 +7666,63 @@ echo "${ECHO_T}no" >&6; }
 fi
 cat >>confdefs.h <<_ACEOF
 #define P_HAS_RECURSIVE_MUTEX ${P_HAS_RECURSIVE_MUTEX}
+_ACEOF
+
+
+
+P_SETPGRP_SYSTEMV=0
+{ echo "$as_me:$LINENO: checking if setpgrp takes no paramaters" >&5
+echo $ECHO_N "checking if setpgrp takes no paramaters... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <unistd.h.h>
+int
+main ()
+{
+pid_t p = setgrp();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  P_SETPGRP_NOPARM=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+if test ${P_SETPGRP_NOPARM} = 1 ; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+cat >>confdefs.h <<_ACEOF
+#define P_SETPGRP_NOPARM ${P_SETPGRP_NOPARM}
 _ACEOF
 
 
@@ -14314,6 +14373,7 @@ echo "${ECHO_T}no" >&6; }
     fi
     ;;
 esac
+
 
 
 
