Moved some preprocessor symbols from the command line to include files Modified to set P_HAS_SEMAPHORES to 0 for Linux kernels >= 2.6 Applied patches for Solaris thanks to Michal Zygmuntowicz

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1860,8 +1860,8 @@ MINOR_VERSION=$MINOR_VERSION
 BUILD_NUMBER=$BUILD_NUMBER
 
 
-{ echo "$as_me:$LINENO: \"PTLib version is ${PWLIB_VERSION}\"" >&5
-echo "$as_me: \"PTLib version is ${PWLIB_VERSION}\"" >&6;};
+{ echo "$as_me:$LINENO: PTLib version is ${PWLIB_VERSION}" >&5
+echo "$as_me: PTLib version is ${PWLIB_VERSION}" >&6;};
 
 cat >>confdefs.h <<_ACEOF
 #define PWLIB_MAJOR $MAJOR_VERSION
@@ -1970,80 +1970,103 @@ OSTYPE=
 case "$target_os" in
   linux*)          OSTYPE=linux ;
                    OSRELEASE=`uname -r` ;
-                   STDCCFLAGS="-DP_LINUX=$OSRELEASE" ;;
+		   OS_TAG="P_LINUX" ;
+		   P_USE_PRAGMA=1 ;
+                   ;;
 
   freebsd* )       OSTYPE=FreeBSD ;
+		   OS_TAG="P_FREEBSD" ;
                    if test "x$OSRELEASE" = "x"; then
                      OSRELEASE=`sysctl -n kern.osreldate` ;
                    fi
-                   STDCCFLAGS="-DP_FREEBSD=${OSRELEASE}" ;;
+		   P_USE_PRAGMA=1 ;
+		   ;;
 
   openbsd* )       OSTYPE=OpenBSD ;
+		   OS_TAG="P_OPENBSD" ;
                    OSRELEASE=`sysctl -n kern.osrevision` ;
 		   ENDLDLIBS="-lossaudio" ;
-                   STDCCFLAGS="$STDCCFLAGS -DP_OPENBSD=$OSRELEASE" ;;
+		   P_USE_PRAGMA=1 ;
+		   ;;
 
   netbsd* )        OSTYPE=NetBSD ;
+		   OS_TAG="P_NETBSD" ;
                    OSRELEASE=`/sbin/sysctl -n kern.osrevision` ;
 		   ENDLDLIBS="-lossaudio" ;
-                   STDCCFLAGS="$STDCCFLAGS -DP_NETBSD=$OSRELEASE" ;;
+		   P_USE_PRAGMA=1 ;
+		   ;;
 
   solaris* | sunos ) OSTYPE=solaris ;
+		   OS_TAG="P_SOLARIS" ;
                    OSRELEASE=`uname -r | sed "s/5\.//g"` ;
-                   STDCCFLAGS="-DP_SOLARIS=$OSRELEASE" ;;
+		   P_USE_PRAGMA=1 ;
+		   ;;
 
   darwin* )	   OSTYPE=Darwin ;
+		   OS_TAG="P_MACOSX" ;
 		   OSRELEASE=`uname -r | sed "s/\.//g"` ;
-                   STDCCFLAGS="-DP_MACOSX=$OSRELEASE -DNO_LONG_DOUBLE" ;
-                   SHAREDLIBEXT="dylib";;
+                   SHAREDLIBEXT="dylib";
+		   P_USE_PRAGMA=1 ;
+		   ;;
 
   * )		   OSTYPE="$target_os" ;
-  		   OSRELEASE=`uname -r` ;
-                   STDCCFLAGS="-DP_UNKNOWN=$OSTYPE_$OSRELEASE" ;
+		   OS_TAG="P_UNKNOWN_OS" ;
+  		   OSRELEASE="${OSTYPE}_`uname -r`" ;
 		   { echo "$as_me:$LINENO: WARNING: \"OS $target_os not recognized - proceed with caution!\"" >&5
-echo "$as_me: WARNING: \"OS $target_os not recognized - proceed with caution!\"" >&2;} ;;
+echo "$as_me: WARNING: \"OS $target_os not recognized - proceed with caution!\"" >&2;} ;
+		   ;;
 esac
 
 MACHTYPE=
 
 case "$target_cpu" in
-   x86 | i686 | i586 | i486 | i386 ) MACHTYPE=x86 ;;
+   x86 | i686 | i586 | i486 | i386 ) MACHTYPE=x86
+                   ;;
 
    x86_64)	   MACHTYPE=x86_64 ;
-                   STDCCFLAGS="$STDCCFLAGS -DP_64BIT" ;;
+		   P_64BIT=1 ;
+		   ;;
 
    alpha | alphaev56) MACHTYPE=alpha ;
-                   STDCCFLAGS="$STDCCFLAGS -DP_64BIT" ;;
+		   P_64BIT=1 ;
+		   ;;
 
-   sparc )         MACHTYPE=sparc ;;
+   sparc )         MACHTYPE=sparc ;
+		   ;;
 
-   powerpc )       MACHTYPE=ppc ;;
+   powerpc )       MACHTYPE=ppc ;
+		   ;;
 
-   powerpc64 )       MACHTYPE=ppc ;
-	     	     STDCCFLAGS="$STDCCFLAGS -DP_64BIT" ;;
+   powerpc64 )     MACHTYPE=ppc ;
+		   P_64BIT=1 ;
+		   ;;
 
    ppc64 )         MACHTYPE=ppc ;
-		   STDCCFLAGS="$STDCCFLAGS -DP_64BIT" ;;
+		   P_64BIT=1 ;
+		   ;;
 
-   ppc )           MACHTYPE=ppc ;;
+   ppc )           MACHTYPE=ppc ;
+		   ;;
 
    ia64)	   MACHTYPE=ia64 ;
-                   STDCCFLAGS="$STDCCFLAGS -DP_64BIT" ;;
+		   P_64BIT=1 ;
+	  	   ;;
 
    s390x)	   MACHTYPE=s390x ;
-                   STDCCFLAGS="$STDCCFLAGS -DP_64BIT" ;;
+		   P_64BIT=1 ;
+		   ;;
 
    * )		   MACHTYPE=$target_cpu ;
 		   { echo "$as_me:$LINENO: WARNING: \"CPU $target_cpu not recognized - proceed with caution!\"" >&5
 echo "$as_me: WARNING: \"CPU $target_cpu not recognized - proceed with caution!\"" >&2;} ;;
 esac
 
-{ echo "$as_me:$LINENO: \"OSTYPE set to $OSTYPE\"" >&5
-echo "$as_me: \"OSTYPE set to $OSTYPE\"" >&6;};
-{ echo "$as_me:$LINENO: \"OSRELEASE set to $OSRELEASE\"" >&5
-echo "$as_me: \"OSRELEASE set to $OSRELEASE\"" >&6;};
-{ echo "$as_me:$LINENO: \"MACHTYPE set to $MACHTYPE\"" >&5
-echo "$as_me: \"MACHTYPE set to $MACHTYPE\"" >&6;};
+{ echo "$as_me:$LINENO: OSTYPE set to $OSTYPE" >&5
+echo "$as_me: OSTYPE set to $OSTYPE" >&6;};
+{ echo "$as_me:$LINENO: OSRELEASE set to $OSRELEASE" >&5
+echo "$as_me: OSRELEASE set to $OSRELEASE" >&6;};
+{ echo "$as_me:$LINENO: MACHTYPE set to $MACHTYPE" >&5
+echo "$as_me: MACHTYPE set to $MACHTYPE" >&6;};
 
 MACHTYPE=$MACHTYPE
 
@@ -2053,6 +2076,58 @@ OSRELEASE=$OSRELEASE
 
 TARGETDIR=$TARGETDIR
 
+
+cat >>confdefs.h <<_ACEOF
+#define $OS_TAG "$OSRELEASE"
+_ACEOF
+
+
+cat >>confdefs.h <<\_ACEOF
+#define PHAS_TEMPLATES 1
+_ACEOF
+
+
+if test "x$P_USE_PRAGMA" != "x" ; then
+  cat >>confdefs.h <<\_ACEOF
+#define P_USE_PRAGMA 1
+_ACEOF
+
+fi
+if test "x$P_64BIT" != "x" ; then
+  cat >>confdefs.h <<\_ACEOF
+#define P_64BIT 1
+_ACEOF
+
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define P_PTHREADS 1
+_ACEOF
+
+if test ${OSTYPE} != Linux ; then
+  SRC_RELEASE=`uname -r`
+  VERSION=`echo $SRC_RELEASE | sed -n -e 's/^\([0-9]*\).*/\1/p'`
+  PATCHLEVEL=`echo $SRC_RELEASE | sed -n -e 's/.*\.\([0-9]*\)\..*/\1/p'`
+  if test \( $VERSION -le 2 \) -a \( $PATCHLEVEL -lt 6 \) ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define P_HAS_SEMAPHORES 1
+_ACEOF
+
+    { echo "$as_me:$LINENO: P_HAS_SEMAPHORES = 1 as kernel $SRC_RELEASE < 2.6" >&5
+echo "$as_me: P_HAS_SEMAPHORES = 1 as kernel $SRC_RELEASE < 2.6" >&6;};
+  else
+    { echo "$as_me:$LINENO: P_HAS_SEMAPHORES = 0 as kernel $SRC_RELEASE >= 2.6" >&5
+echo "$as_me: P_HAS_SEMAPHORES = 0 as kernel $SRC_RELEASE >= 2.6" >&6;};
+  fi
+elif test ${OSTYPE} != Darwin ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define P_HAS_SEMAPHORES 1
+_ACEOF
+
+fi
 
 
 if test "x${SHAREDLIBEXT}" = "x" ; then
@@ -3170,19 +3245,6 @@ echo "$as_me: error: must have pthreads!" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-
-cat >>confdefs.h <<\_ACEOF
-#define P_PTHREADS 1
-_ACEOF
-
-if test ${OSTYPE} != Darwin ; then
-
-cat >>confdefs.h <<\_ACEOF
-#define P_HAS_SEMAPHORES 1
-_ACEOF
-
-fi
-
 echo "$as_me:$LINENO: checking for regcomp" >&5
 echo $ECHO_N "checking for regcomp... $ECHO_C" >&6
 if test "${ac_cv_func_regcomp+set}" = set; then
@@ -4276,6 +4338,7 @@ echo $ECHO_N "checking for res_search in -lresolv... $ECHO_C" >&6
   LIBS="-lresolv"
   cat >conftest.$ac_ext <<_ACEOF
 
+#include <netinet/in.h>
 #include <resolv.h>
 int main(int argc,char **argv){
  res_search (NULL, 0, 0, NULL, 0);
@@ -4567,14 +4630,19 @@ fi
 
 done
 
-  if test "${HAS_OPENLDAP:-unset}" != "unset" ; then
+
+    if test "${OSTYPE:-unknown}" = "solaris"; then
+    OPENLDAPSYSLIBS=-lposix4
+  fi
+
+    if test "${HAS_OPENLDAP:-unset}" != "unset" ; then
     echo "$as_me:$LINENO: checking for ldap_open in -lldap" >&5
 echo $ECHO_N "checking for ldap_open in -lldap... $ECHO_C" >&6
 if test "${ac_cv_lib_ldap_ldap_open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lldap -llber $RESOLVER_LIBS $LIBS"
+LIBS="-lldap -llber -lldap_r $RESOLVER_LIBS $ENDLDLIBS $OPENLDAPSYSLIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 /* confdefs.h.  */
@@ -4653,6 +4721,66 @@ fi
     if test "${HAS_OPENLDAP:-unset}" != "unset" ; then
       OPENLDAPINCLUDEDIR=/usr/local/include
       OPENLDAPLIBDIR=/usr/local/lib
+      echo "$as_me:$LINENO: checking for ldap_open in -lldap" >&5
+echo $ECHO_N "checking for ldap_open in -lldap... $ECHO_C" >&6
+if test "${ac_cv_lib_ldap_ldap_open+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lldap -L/usr/local/lib -llber -lldap_r $RESOLVER_LIBS $ENDLDLIBS $OPENLDAPSYSLIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char ldap_open ();
+int
+main ()
+{
+ldap_open ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_ldap_ldap_open=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_ldap_ldap_open=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_ldap_ldap_open" >&5
+echo "${ECHO_T}$ac_cv_lib_ldap_ldap_open" >&6
+if test $ac_cv_lib_ldap_ldap_open = yes; then
+  HAS_OPENLDAP=1
+else
+  HAS_OPENLDAP=
+fi
+
     fi
   fi
 fi
@@ -4671,7 +4799,136 @@ _ACEOF
   if test ${OPENLDAPLIBDIR:-unset} != "unset" ; then
     LDFLAGS="$LDFLAGS -L${OPENLDAPLIBDIR}"
   fi
-  ENDLDLIBS="$ENDLDLIBS -lldap -lldap_r -llber -lsasl"
+
+      echo "$as_me:$LINENO: checking for sasl_version in -lsasl" >&5
+echo $ECHO_N "checking for sasl_version in -lsasl... $ECHO_C" >&6
+if test "${ac_cv_lib_sasl_sasl_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsasl $LDFLAGS -llber -lldap -lldap_r $RESOLVER_LIBS $ENDLDLIBS $OPENDLAPSYSLIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sasl_version ();
+int
+main ()
+{
+sasl_version ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_sasl_sasl_version=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_sasl_sasl_version=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_sasl_sasl_version" >&5
+echo "${ECHO_T}$ac_cv_lib_sasl_sasl_version" >&6
+if test $ac_cv_lib_sasl_sasl_version = yes; then
+  HAS_SASL=1
+else
+  HAS_SASL=
+fi
+
+  if test ${HAS_SASL:-unset} = "unset" ; then
+    echo "$as_me:$LINENO: checking for sasl_version in -lsasl2" >&5
+echo $ECHO_N "checking for sasl_version in -lsasl2... $ECHO_C" >&6
+if test "${ac_cv_lib_sasl2_sasl_version+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsasl2 $LDFLAGS -llber -lldap -lldap_r $RESOLVER_LIBS $ENDLDLIBS $OPENDLAPSYSLIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char sasl_version ();
+int
+main ()
+{
+sasl_version ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_sasl2_sasl_version=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_sasl2_sasl_version=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_sasl2_sasl_version" >&5
+echo "${ECHO_T}$ac_cv_lib_sasl2_sasl_version" >&6
+if test $ac_cv_lib_sasl2_sasl_version = yes; then
+  HAS_SASL2=1
+else
+  HAS_SASL2=
+fi
+
+  fi
+  if test ${HAS_SASL:-unset} != "unset" ; then
+    ENDLDLIBS="$ENDLDLIBS -lldap -lldap_r -llber -lsasl"
+  elif test ${HAS_SASL2:-unset} != "unset" ; then
+    ENDLDLIBS="$ENDLDLIBS -lldap -lldap_r -llber -lsasl2"
+  else
+    ENDLDLIBS="$ENDLDLIBS -lldap -lldap_r -llber"
+  fi
 fi
 
 
@@ -4866,8 +5123,6 @@ rm -f conftest.$ac_objext conftest.$ac_ext
       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
       SSLCCFLAGS=" -DOPENSSL_NO_KRB5"
-      P_STATIC_LDFLAGS="-L/usr/kerboros/lib"
-      P_STATIC_ENDLDLIBS="-lkrb5 -lk5crypto -lcom_err"
     else
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -6076,8 +6331,8 @@ cat >>confdefs.h <<\_ACEOF
 #define NO_VIDEO_CAPTURE 1
 _ACEOF
 
-  { echo "$as_me:$LINENO: \"No Video Capture support\"" >&5
-echo "$as_me: \"No Video Capture support\"" >&6;}
+  { echo "$as_me:$LINENO: No Video Capture support" >&5
+echo "$as_me: No Video Capture support" >&6;}
 fi
 
 
