Add detection of Linux network interfaces changes via NetLink socket
git-svn-id: svn://svn.code.sf.net/p/opalvoip/code/ptlib/trunk@22880 023b2edf-31b2-4de3-b41e-bca80c47788f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6905,6 +6905,70 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+P_HAS_NETLINK=0
+{ echo "$as_me:$LINENO: checking for NetLink support" >&5
+echo $ECHO_N "checking for NetLink support... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <asm/types.h>
+                #include <sys/socket.h>
+                #include <linux/netlink.h>
+                #include <linux/rtnetlink.h>
+                #include <linux/genetlink.h>
+                #include <memory.h>
+int
+main ()
+{
+struct sockaddr_nl sa; memset(&sa, 0, sizeof(sa));
+                sa.nl_family = AF_NETLINK; sa.nl_groups = RTMGRP_LINK | RTMGRP_IPV4_IFADDR;
+                int fd = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  P_HAS_NETLINK=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+if test "${P_HAS_NETLINK}" = "1" ; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  cat >>confdefs.h <<\_ACEOF
+#define P_HAS_NETLINK 1
+_ACEOF
+
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
 P_HAS_STL_STREAMS=0
 { echo "$as_me:$LINENO: checking if using STL streams" >&5
 echo $ECHO_N "checking if using STL streams... $ECHO_C" >&6; }
