Added --enable-opal.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -848,6 +848,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-minsize        minimise the size of the lib by disabling least used options
   --enable-openh323       include only options needed with openh323
+  --enable-opal           include only options needed with opal
   --enable-internalregex  force internal regex library
   --enable-plugins        enable plugin support
   --disable-resolver      disable DNS resolver support
@@ -3927,6 +3928,11 @@ if test "${enable_openh323+set}" = set; then
   enableval="$enable_openh323"
 
 fi;
+# Check whether --enable-opal or --disable-opal was given.
+if test "${enable_opal+set}" = set; then
+  enableval="$enable_opal"
+
+fi;
 
 default_resolver=yes
 default_openldap=yes
@@ -3961,7 +3967,7 @@ default_oss=yes
 default_ipv6=yes
 default_qos=yes
 
-if test "${enable_openh323}x" = "yesx" ; then
+if test "${enable_openh323}x" = "yesx" -o "${enable_opal}x" = "yesx" ; then
   default_resolver=yes
   default_openldap=yes
   default_openssl=yes
@@ -4406,6 +4412,66 @@ echo "${ECHO_T}yes" >&6
   else
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+  fi
+fi
+
+if test "${P_HAS_SEMAPHORES}x" == "x" ; then
+
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <semaphore.h>
+int
+main ()
+{
+sem_t *s = sem_open("test", O_CREAT)
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  P_HAS_NAMED_SEMAPHORES=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+  echo "$as_me:$LINENO: checking if named semaphores are available" >&5
+echo $ECHO_N "checking if named semaphores are available... $ECHO_C" >&6
+  if test "${P_HAS_NAMED_SEMAPHORES}x" != "x"; then
+    cat >>confdefs.h <<\_ACEOF
+#define P_HAS_NAMED_SEMAPHORES 1
+_ACEOF
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
     { echo "$as_me:$LINENO: WARNING: This host does not support semaphores which are essential" >&5
 echo "$as_me: WARNING: This host does not support semaphores which are essential" >&2;}
     { echo "$as_me:$LINENO: WARNING: to implement 'critical sections'. This feature was added" >&5
@@ -4749,8 +4815,61 @@ if test ${P_HAS_RECURSIVE_MUTEX} = 1 ; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 else
-  echo "$as_me:$LINENO: result: no" >&5
+  if test ${OSTYPE} == Darwin ; then
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pthread.h>
+int
+main ()
+{
+pthread_mutexattr_t attr; pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  P_HAS_RECURSIVE_MUTEX=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+    if test ${P_HAS_RECURSIVE_MUTEX} = 1 ; then
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    else
+      echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
+    fi
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
 fi
 cat >>confdefs.h <<_ACEOF
 #define P_HAS_RECURSIVE_MUTEX ${P_HAS_RECURSIVE_MUTEX}
