First hack at a ptlib plugin for pulse audio. No volume options available - pulse wants you to use the desktop or system provided widgets. This is a simple simple test, and is provided to let users try out pulse audio and see how it works. this does not go via alsa plugins, so should give "reasonable" performance.

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -680,6 +680,7 @@ EGREP
 HAS_ALSA
 HAS_ESD
 HAS_OSS
+HAS_PULSE
 HAS_SUNAUDIO
 HAS_V4L
 V4L2_CFLAGS
@@ -1282,6 +1283,7 @@ disable plugin support]
   --enable-alsa           enable ALSA audio support
   --enable-esd            enable ESD audio support
   --enable-oss            enable OSS audio support
+  --enable-pulse            enable Pulse audio support
   --enable-sunaudio            enable  Sun audio support
   --disable-video         disable video device support
   --enable-v4l            enable V4L video support
@@ -4300,6 +4302,159 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+# Check whether --enable-pulse was given.
+if test "${enable_pulse+set}" = set; then
+  enableval=$enable_pulse;
+else
+  enable_pulse=yes
+fi
+
+
+if test "${enable_pulse}z" = "yesz" ; then
+  if test "${ac_cv_header_pulse_simple_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for pulse/simple.h" >&5
+echo $ECHO_N "checking for pulse/simple.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_pulse_simple_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_pulse_simple_h" >&5
+echo "${ECHO_T}$ac_cv_header_pulse_simple_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking pulse/simple.h usability" >&5
+echo $ECHO_N "checking pulse/simple.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <pulse/simple.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking pulse/simple.h presence" >&5
+echo $ECHO_N "checking pulse/simple.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pulse/simple.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: pulse/simple.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: pulse/simple.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: pulse/simple.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: pulse/simple.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: pulse/simple.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: pulse/simple.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: pulse/simple.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: pulse/simple.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: pulse/simple.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for pulse/simple.h" >&5
+echo $ECHO_N "checking for pulse/simple.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_pulse_simple_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_pulse_simple_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_pulse_simple_h" >&5
+echo "${ECHO_T}$ac_cv_header_pulse_simple_h" >&6; }
+
+fi
+if test $ac_cv_header_pulse_simple_h = yes; then
+  SNDCARDHDR=1
+fi
+
+
+  { echo "$as_me:$LINENO: checking for Pulse sound support" >&5
+echo $ECHO_N "checking for Pulse sound support... $ECHO_C" >&6; }
+  if test "${SNDCARDHDR}z" != "z"; then
+    HAS_PULSE=1
+
+    { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+  else
+    { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+  fi
+fi
+
+
 # Check whether --enable-sunaudio was given.
 if test "${enable_sunaudio+set}" = set; then
   enableval=$enable_sunaudio;
@@ -6864,6 +7019,7 @@ EGREP!$EGREP$ac_delim
 HAS_ALSA!$HAS_ALSA$ac_delim
 HAS_ESD!$HAS_ESD$ac_delim
 HAS_OSS!$HAS_OSS$ac_delim
+HAS_PULSE!$HAS_PULSE$ac_delim
 HAS_SUNAUDIO!$HAS_SUNAUDIO$ac_delim
 HAS_V4L!$HAS_V4L$ac_delim
 V4L2_CFLAGS!$V4L2_CFLAGS$ac_delim
@@ -6877,7 +7033,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 78; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 79; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
