Updated for changes to configure.in

diff --git a/plugins/configure b/plugins/configure
--- a/plugins/configure
+++ b/plugins/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT PWLIBDIR PWINSTDIR INSTALLPREFIX LIBDIR CC CFLAGS ac_ct_CC CPP EGREP HAS_ALSA HAS_OSS HAS_V4L HAS_BSDVIDEOCAP HAS_AVC1394 LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT PWLIBDIR PWINSTDIR INSTALLPREFIX LIBDIR CC CFLAGS ac_ct_CC CPP EGREP HAS_ALSA HAS_OSS HAS_V4L HAS_BSDVIDEOCAP HAS_AVC1394 HAS_DC1394 LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -852,6 +852,7 @@ Optional Features:
   --enable-v4l            enable V4L video support
   --enable-bsdvideo       enable BSD video support
   --enable-avc            enable IEEE1394/AVC video support
+  --enable-dc             enable IEEE1394/DC video support
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -4273,6 +4274,297 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+# Check whether --enable-dc or --disable-dc was given.
+if test "${enable_dc+set}" = set; then
+  enableval="$enable_dc"
+
+else
+  enable_dc=yes
+fi;
+
+if test "$enable_dc" = "yes" ; then
+  if test "${ac_cv_header_libdc1394_dc1394_control_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for libdc1394/dc1394_control.h" >&5
+echo $ECHO_N "checking for libdc1394/dc1394_control.h... $ECHO_C" >&6
+if test "${ac_cv_header_libdc1394_dc1394_control_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_libdc1394_dc1394_control_h" >&5
+echo "${ECHO_T}$ac_cv_header_libdc1394_dc1394_control_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking libdc1394/dc1394_control.h usability" >&5
+echo $ECHO_N "checking libdc1394/dc1394_control.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <libdc1394/dc1394_control.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking libdc1394/dc1394_control.h presence" >&5
+echo $ECHO_N "checking libdc1394/dc1394_control.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libdc1394/dc1394_control.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: libdc1394/dc1394_control.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: libdc1394/dc1394_control.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libdc1394/dc1394_control.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libdc1394/dc1394_control.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: libdc1394/dc1394_control.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: libdc1394/dc1394_control.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libdc1394/dc1394_control.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: libdc1394/dc1394_control.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libdc1394/dc1394_control.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libdc1394/dc1394_control.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for libdc1394/dc1394_control.h" >&5
+echo $ECHO_N "checking for libdc1394/dc1394_control.h... $ECHO_C" >&6
+if test "${ac_cv_header_libdc1394_dc1394_control_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_libdc1394_dc1394_control_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_libdc1394_dc1394_control_h" >&5
+echo "${ECHO_T}$ac_cv_header_libdc1394_dc1394_control_h" >&6
+
+fi
+if test $ac_cv_header_libdc1394_dc1394_control_h = yes; then
+  DC1394HDR=1
+fi
+
+
+  if test "${ac_cv_header_libraw1394_raw1394_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for libraw1394/raw1394.h" >&5
+echo $ECHO_N "checking for libraw1394/raw1394.h... $ECHO_C" >&6
+if test "${ac_cv_header_libraw1394_raw1394_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_libraw1394_raw1394_h" >&5
+echo "${ECHO_T}$ac_cv_header_libraw1394_raw1394_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking libraw1394/raw1394.h usability" >&5
+echo $ECHO_N "checking libraw1394/raw1394.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <libraw1394/raw1394.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking libraw1394/raw1394.h presence" >&5
+echo $ECHO_N "checking libraw1394/raw1394.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <libraw1394/raw1394.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: libraw1394/raw1394.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: libraw1394/raw1394.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libraw1394/raw1394.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libraw1394/raw1394.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: libraw1394/raw1394.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: libraw1394/raw1394.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libraw1394/raw1394.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: libraw1394/raw1394.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: libraw1394/raw1394.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: libraw1394/raw1394.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for libraw1394/raw1394.h" >&5
+echo $ECHO_N "checking for libraw1394/raw1394.h... $ECHO_C" >&6
+if test "${ac_cv_header_libraw1394_raw1394_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_libraw1394_raw1394_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_libraw1394_raw1394_h" >&5
+echo "${ECHO_T}$ac_cv_header_libraw1394_raw1394_h" >&6
+
+fi
+if test $ac_cv_header_libraw1394_raw1394_h = yes; then
+  RAW1394HDR=1
+fi
+
+
+  echo "$as_me:$LINENO: checking for IEEE1394/DC video support" >&5
+echo $ECHO_N "checking for IEEE1394/DC video support... $ECHO_C" >&6
+  if test "${DC1394HDR:-unset}" != "unset" -a ${RAW1394HDR:-unset} != "unset"; then
+    HAS_DC1394=1
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+fi
+
+
           ac_config_files="$ac_config_files Makefile"
 
 
@@ -4930,6 +5222,7 @@ s,@HAS_OSS@,$HAS_OSS,;t t
 s,@HAS_V4L@,$HAS_V4L,;t t
 s,@HAS_BSDVIDEOCAP@,$HAS_BSDVIDEOCAP,;t t
 s,@HAS_AVC1394@,$HAS_AVC1394,;t t
+s,@HAS_DC1394@,$HAS_DC1394,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
